### ISSUE TITLE
Picoez to JTAG adapter info

### ISSUE THREAD

**Issue by neon5d** [RHSResearchLLC/uEVB#14]
Hello,

Can you give more detailed information on what connector types are used for the pico (6 pins) to JTAG (14 pins, 2x7) adapter?
My JTAG cable does not fit the JTAG socket. I need to replace it.
Thank you

**Comment by RHSResearchLLC** [comment]
Hello,

Here are the design files (schematic, bill of materials, and gerbers):

[Pico-JTAG-BOM.xlsx](https://github.com/RHSResearchLLC/NiteFury-and-LiteFury/files/6689318/Pico-JTAG-BOM.xlsx)
[Pico-JTAG.pdf](https://github.com/RHSResearchLLC/NiteFury-and-LiteFury/files/6689320/Pico-JTAG.pdf)
[Pico-JTAG-Gerber-X2.zip](https://github.com/RHSResearchLLC/NiteFury-and-LiteFury/files/6689321/Pico-JTAG-Gerber-X2.zip)

**Comment by RHSResearchLLC** [comment]
Here is the schematic for the 6-pin Pico-ezmate cable as well

[pjc-1.pdf](https://github.com/RHSResearchLLC/NiteFury-and-LiteFury/files/6689327/pjc-1.pdf)

**Comment by neon5d** [comment]
These are what I needed. Thank you.
