### ISSUE TITLE
LVDS connection (DF52-20P)

### ISSUE THREAD

**Issue by neon5d** [RHSResearchLLC/uEVB#16]
Hello,

I am trying to connect DF52-20P.
The right part is DF52-20P-0.8C.
I used the cable (DF52-2832PF157). 
The cable is quite expensive and it has an individual cable for 20 pins.
Do you have any other solution for the DF52-20P connection?
Thank you,

**Comment by RHSResearchLLC** [comment]
Hello neon5d,

Unfortunately I don't have another solution. Mouser used to sell a pre-built 20-pin cable, but they don't anymore; they just sell individual pre-crimped leads.

**Comment by neon5d** [comment]
Thank you for confirmation.
