### ISSUE TITLE
Enable over-temperature shutdown for LiteFury

### ISSUE THREAD

**Issue by trosenkranz** [RHSResearchLLC/uEVB#18]
As already asked in #2, please also enable over-temperature shutdown for the LiteFury sample project. (Sample-Projects/Project-0/FPGA-A100T-2/)

Thanks
Tobias

**Comment by BradleyConn** [comment]
It would also be great to implement LTC3636 temperature monitoring in the sample project!

**Comment by RHSResearchLLC** [comment]
Fixed in latest release- over-temperature shutdown enabled
