### ISSUE TITLE
Enable over-temperature shutdown

### ISSUE THREAD

**Issue by HackerFoo** [RHSResearchLLC/uEVB#2]
It might be a good idea to enable over-temperature shutdown for Project-0:
```
# XDC Constraint
set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]
```

Which I think is the same as: Edit Device Properties > Configuration > Enable over-termperature shutdown = ENABLE

**Comment by RHSResearchLLC** [comment]
Agreed, this is a good idea. I've added the constraint- I'll be checking in new MCS soon. Thanks.
