### ISSUE TITLE
Where to find/how to change "board version" (aka `board_pvrsn`)?

### ISSUE THREAD

**Issue by mablinov** [RHSResearchLLC/uEVB#23]
Probably a stupid question, but I can't figure out where to find the right value to put for the "board version" parameter that is required for the [`furytest.sh`](https://github.com/RHSResearchLLC/NiteFury-and-LiteFury/blob/master/Sample-Projects/Project-0/Host/fury-test.sh) script.

In the [`test-general.py`](https://github.com/RHSResearchLLC/NiteFury-and-LiteFury/blob/9fc9f1bae6c06523d46470fc309b73e7015aa9fd/Sample-Projects/Project-0/Host/test-general.py#L50) its referred to as the `board_vrsn` parameter. I added a line to print out the `pvrsn` read back from the board, and it appears to be assigned to `2` - Where is this configured from the Vivado side of things?

**Comment by RHSResearchLLC** [comment]
In the block diagram, expand the "GPIO_regs" block, then there are constants for "Model" and "Version"

**Comment by RHSResearchLLC** [comment]
![image](https://user-images.githubusercontent.com/28763904/222755330-744ebd6f-b8ca-4544-bd46-0ea6c7f51c0a.png)

**Comment by RHSResearchLLC** [comment]
![image](https://user-images.githubusercontent.com/28763904/222755498-1c75d157-86d3-4140-b4cb-9b0e485c2ee2.png)

**Comment by mablinov** [comment]
Got it, thanks!
