### ISSUE TITLE
About NiteFury with Integrated Heatsink from crowd supply.

### ISSUE THREAD

**Issue by mopplayer** [RHSResearchLLC/uEVB#26]
Hi, is there any difference between NiteFury-II and NiteFury-I (NiteFury with Integrated Heatsink from crowd supply)?

I have seen that it only has 512MB DDR3 on board, right?
Are there other changes?

Thank you very much.

**Comment by RHSResearchLLC** [comment]
Hello,

The main difference is the heatsink: the -II has a large heatsink. The
original design is discontinued; the heatsink didn't work well enough and
it was a lot of labor to assemble.

Other than that, the design is the same, aside from various
bill-of-materials only changes (DDR capacity, FPGA, etc)

Best regards,

Dave
