### ISSUE TITLE
NiteFurry II with M.2 case 

### ISSUE THREAD

**Issue by WannaBeKratos** [RHSResearchLLC/uEVB#27]
Is it possible to take the heat sink off and put it in a case like this one [DOCKCASE](https://www.amazon.com/DOCKCASE-Visual-Enclosure-Support-Prevents/dp/B09Z2CFDYQ/ref=sr_1_15?crid=WB025EM40J73&keywords=m.2+case&qid=1691698881&sprefix=m.2+case%2Caps%2C155&sr=8-15) and have it work via USB ?

**Comment by RHSResearchLLC** [comment]
The Nitefury/Litefury heatsink cannot be removed without destroying the board; the heatsink is glued to the FPGA and the glue is stronger than the solder attachment to the PCB. Also the heatsink is necessary; the PCIe block uses a few watts which cannot be safely dissipated without a heatsink.
