### ISSUE TITLE
Which partname to set for NiteFury: XC7A200T-2FBG484E or XC7A200T-FBG484

### ISSUE THREAD

**Issue by mayureshw** [RHSResearchLLC/uEVB#32]
Readme of this repository shows XC7A200T-2FBG484E, but Vivado rejects this as invalid partname when creating bitstream. (I am using all tcl scripts, no UI.)

In the following xdc file in this repository I found partname XC7A200T-FBG484
Sample-Projects/Project-0/FPGA/Nitefury-II/project/project.srcs/sources_1/bd/Top/ip/Top_mig_7series_0_0/Top_mig_7series_0_0/example_design/par/example_top.xdc

This is accepted by Vivado, but a simple design to just switch on or off an LED is transferred to the expected effect on LED doesn't happen.

In my Vivado installation I find following partnames with string fbg484

xc7a200tfbg484-1
xc7a200tfbg484-2
xc7a200tfbg484-2L
xc7a200tfbg484-3
xc7a200tifbg484-1L
xc7a200tlfbg484-2L

get_property PART [current_hw_device]
shows xc7a200t

This partname is accepted, but still I am unable to get any indication on the LEDs.

In my design I have just set '1' on LED_A1 through LED_A4 and LED_M2. I have used constraint files copied from this directory: Sample-Projects/Project-0/FPGA/Nitefury-II/project/project.srcs/constrs_1/imports/constraints

Some of the sample projects in this repo show: xc7a200tfbg484-2. With that also, I don't seem to get the LEDs lit.

My Vivado version is:  v2022.2

**Comment by mayureshw** [comment]
Ah! '0' means ON for LED on this board. I can now control LED_A*

But what about LED_M2, it doesn't seem to matter whether I set it to '1' or '0'.

**Comment by RHSResearchLLC** [comment]
xc7a200tfbg484-2 is the right part.

The LED_M2 is not on the board- it toggles the LED line on the M.2 connector, which usually isn't connected to anything. Some motherboards will pin this to a header or LED.
