### ISSUE TITLE
Interfacing ADC with Nitefury II via DF52

### ISSUE THREAD

**Issue by neerajkc** [RHSResearchLLC/uEVB#33]
The LVDS lines on the DF52 connector interface to pins that are not clock capable (none of the pins are MRCC/SRCC). I could see DQS lanes though in the two banks. Is there a way I can use the DF52 lanes to interface a high speed multichannel ADC?
It's a 65MSPS ADC in serial LVDS mode and outputs a data_clock, frame_clock, and data. I need to use ISERDES2 primitives to deserialise the data into 12-bit samples.

**Comment by RHSResearchLLC** [comment]
They aren't clock-capable but they are LVDS pairs. I'm not familiar with that chip but yeah if you need 3 LVDS pairs to interface to it, you should have no problem
