### ISSUE TITLE
Is loading of Top_wrapper.bit over JTAG supposed to work?

### ISSUE THREAD

**Issue by mayureshw** [RHSResearchLLC/uEVB#38]
The sample project build produces the following bitstream file:

NiteFury-and-LiteFury/Sample-Projects/Project-0/FPGA/Nitefury-II/project/project.runs/impl_1/Top_wrapper.bit

Then I am transferring this to the hardware over JTAG using Tcl command: program_hw_devices.

This leads to lspci showing: "Unknown header type 7f"

"echo 1 > /sys/bus/pci/rescan" doesn't help here.

Invoking load_driver afresh leads to

Error: The Kernel module installed correctly, but no devices were recognized.
 FAILED

What exactly is the issue here - is .bit file supposed to work? Is it an issue with re-scanning not happening properly? Or something else?

**Comment by mayureshw** [comment]
Would like to mention that I have built the sample project on Vivado 2022.2. I had to invoke upgrade_ip to upgrade the ips to the current version. That's the only 'change' if at all to the sample design.

**Comment by mayureshw** [comment]
This is quite like the following issue. Can @bipingamiyv please share what the fix was. It will be immensely useful to all users of nitefury. The comment just says "it's done".

https://github.com/RHSResearchLLC/NiteFury-and-LiteFury/issues/20#issuecomment-1420478783

**Comment by mayureshw** [comment]
As illustrated in this[1] article, 'reset' does not solve the problem

remove + rescan also does not solve it

In fact after 'remove' if I reboot the host, the device doesn't show up in lspci again. It shows up again only after power cycle.

[1] https://cubiclenate.com/2019/10/31/power-cycling-pcie-devices-from-the-command-line/

**Comment by mayureshw** [comment]
Update: If I use the stock bitstream from the github repo i.e. NiteFury-and-LiteFury/Sample-Projects/Project-0/FPGA/Nitefury-II/mcs/out.bin "echo 1 > /sys/bus/pci/rescan" DOES work and it restores the lspci output.

So there is something wrong with the bitstream built using Vivado 2022.2. What is it? Is any IP broken? Has anyone succeeded in getting the stock design work under 2022.2?

My steps to build were:

1. open_project project.xpr. This automatically upgrades the project to current vivado version.
2. upgrade_ip [get_ips]. This was needed as recommended during above step to upgrade the ips to the current version
3. ../../common/Scripts/rebuild.tcl and the build.tcl (as advised on this github project page)

The stock bin file has size 3235252 bytes and the newly generated by above step has size 3050500 bytes.

**Comment by mayureshw** [comment]
If I compare what configurable options changed in IP Top_xdma_0_0 due to upgrade_ip, the following new options appear with their default values.

                                                              > all_speeds_all_sides NO
                                                              > enable_pcie_debug_ports False
                                                              > pf0_pm_cap_pmesupport_d0 false
                                                              > pf0_pm_cap_pmesupport_d1 false
                                                              > pf0_pm_cap_pmesupport_d3hot false
                                                              > pf0_pm_cap_supp_d1_state false

**Comment by mayureshw** [comment]
Sharing what I did, in case someone hits this page.

Thanks @bipingamiyv for confirming that the issue relates with early constraints. However I did not find the generated xdc file in project.xpr to changes its order to normal. I am a entirely command line user and have never launched Vivado GUI.

In build.tcl to launch_runs command I added option -scripts_only

This generated script Top_wrapper.tcl

In this script, just before place_design I added 'source pre-place.tcl'

In pre-place.tcl I placed the LOC constraints from early.xdc and before them I just added reset_property for the same cells.

Now the generated bitstream works for me. Even tried "remove and rescan". On remove lspci output goes away and on rescan it comes back. So things are working now.

**Comment by WolverinDEV** [comment]
Just in case anyone stumbles across this issue:  
The `PROCESSING_ORDER` of `early.xdc` must be changed to `EARLY` in the constraint file's properties.

<img width="387" height="750" alt="Image" src="https://github.com/user-attachments/assets/128975b3-dd21-41ff-b0a4-26556ccc60aa" />
