### ISSUE TITLE
Will this work without a heatsink?

### ISSUE THREAD

**Issue by shawnl** [RHSResearchLLC/uEVB#5]
That massive heatsink will not fit in my thinkpad. On the other hand it has a steel case that it would rest against, and you merged the poweroff on overheat patch.

**Comment by RHSResearchLLC** [comment]
Probably not. The Artix FPGAs seem to run hot. Maybe if your bitstream is low power, and you drop to 1 PCIe lane instead of 4, you might have a chance.
